[build]
  base = "apps/new-portfolio"
  publish = "apps/new-portfolio/dist"
  command = "pnpm --filter new-portfolio... run generate"

[functions]
  directory = "apps/new-portfolio/.output/functions"
