name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - name: my-portfolio
            path: apps/my-portfolio
            site_id: 982a59e1-0ec4-4798-adf2-2177890cd318
            node-version: 22
          - name: new-portfolio
            path: apps/new-portfolio
            site_id: 6633f892-4bf5-4663-b8fa-8c8a2c61c61f
            node-version: 22
          - name: DotiPad
            path: apps/DotiPad
            site_id: b8c6c847-c081-47b3-ae42-e7c9f32b4f4e

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Prepare starter module
        run: pnpm -F nuxt-starter install && pnpm -F nuxt-starter build

      - name: Install dependencies
        run: pnpm install

      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          npx netlify deploy \
            --prod \
            --cwd ${{ matrix.app.path }} \
            --dir ${{ matrix.app.path }}/dist \
            --functions ${{ matrix.app.path }}/.output/server \
            --site ${{ matrix.app.site_id }} \
            --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}
