name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest

    outputs:
      cache-hit: ${{ steps.cache-starter.outputs.cache-hit }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Cache starter build
        id: cache-starter
        uses: actions/cache@v4
        with:
          path: modules/starter/dist
          key: starter-${{ hashFiles('modules/starter/package.json', 'modules/starter/pnpm-lock.yaml', 'modules/starter/src/**') }}

      - name: Build starter module (if cache missed)
        if: steps.cache-starter.outputs.cache-hit != 'true'
        run: |
          pnpm -F nuxt-starter install
          pnpm -F nuxt-starter build

      - name: Upload built starter module
        uses: actions/upload-artifact@v4
        with:
          name: starter-build
          path: modules/starter/dist

  deploy:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - name: new-portfolio
            path: apps/new-portfolio
            site_id: 6633f892-4bf5-4663-b8fa-8c8a2c61c61f
            node-version: 22
          - name: DotiPad
            path: apps/DotiPad
            site_id: b8c6c847-c081-47b3-ae42-e7c9f32b4f4e
            node-version: 22

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check for changes in app
        id: check_changes
        run: |
          echo "Checking changes in path: ${{ matrix.app.path }}"
          if git diff --quiet HEAD^ HEAD -- ${{ matrix.app.path }}; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        if: steps.check_changes.outputs.changed == 'true'

      - name: Download starter module build (only if built this run)
        uses: actions/download-artifact@v4
        if: steps.check_changes.outputs.changed == 'true'
        with:
          name: starter-build
          path: modules/starter/dist

      - name: Install dependencies
        # run pnpm install within the app directory by using the matrix path
        run: pnpm install
        if: steps.check_changes.outputs.changed == 'true'

      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          npx netlify deploy \
            --prod \
            --cwd ${{ matrix.app.path }} \
            --dir ${{ matrix.app.path }}/dist \
            --functions .netlify/functions-internal \
            --site ${{ matrix.app.site_id }} \
            --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}
        if: steps.check_changes.outputs.changed == 'true'
