name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - name: new-portfolio
            path: apps/new-portfolio
            site_id_secret: NETLIFY_SITE_ID_PORTFOLIO_V2
            node-version: 20
          # - name: another-app
          #   path: apps/another-app
          #   site_id_secret: NETLIFY_SITE_ID_OTHER

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.app.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.app.node-version }}
          cache: 'pnpm'

      - name: Enable Corepack and install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install

      # - name: Install dependencies (app + module)
      #   run: |
      #     corepack enable
      #     corepack prepare pnpm@latest --activate
      #     pnpm --filter ./modules/nuxt-starter... --filter ./apps/new-portfolio... install

      - name: Build ${{ matrix.app.name }}
        run: |
          pnpm --filter ./${{ matrix.app.path }}... run build

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets[matrix.app.site_id_secret] }}
        run: |
          npx netlify deploy \
            --auth $NETLIFY_AUTH_TOKEN \
            --site $NETLIFY_SITE_ID \
            --dir=${{ matrix.app.path }}/.output/public \
            --prod
