name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - name: new-portfolio
            path: apps/new-portfolio
            site_id_secret: NETLIFY_SITE_ID_PORTFOLIO_V2
            node-version: 22
          # - name: another-app
          #   path: apps/another-app
          #   site_id_secret: NETLIFY_SITE_ID_OTHER

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 22

      # - name: Install pnpm
      #   uses: pnpm/action-setup@v4

      # - name: Install Netlify
      #   run: npm install netlify-cli@22.2.2 -g

      # - name: Enable Corepack and install pnpm
      #   run: |
      #     corepack enable
      #     corepack prepare pnpm@latest --activate

      - name: Prepare starter module
        run: pnpm -F nuxt-starter install && pnpm -F nuxt-starter dev:prepare

      - name: Install dependencies
        run: pnpm install

      # - name: Install dependencies (app + module)
      #   run: |
      #     corepack enable
      #     corepack prepare pnpm@latest --activate
      #     pnpm --filter ./modules/nuxt-starter... --filter ./apps/new-portfolio... install

      # - name: Build ${{ matrix.app.name }}
      #   run: |
      #     pnpm --filter ./${{ matrix.app.path }}... run build

      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          npx netlify deploy \
            --cwd ${{ matrix.app.path }} \
            --dir ${{ matrix.app.path }}/dist \
            --site ${{ secrets[matrix.app.site_id_secret] }} \
            --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}
